### ISSUE TITLE
Broken build - Could not find package + behat issue

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-elemental-bannerblock#66]
~Blocked on silverstripe-elemental having php 8 support~ See https://github.com/silverstripe/silverstripe-elemental-bannerblock/issues/66#issuecomment-837798871

Elemental 2.2 + 2

https://travis-ci.com/github/silverstripe/silverstripe-elemental-bannerblock/jobs/490659633

```
[InvalidArgumentException]  

  Could not find package ||.  
```

Probably just an issue with $REQUIRE_EXTRA in .travis.yml

### PRs:
- [x] https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/67

**Comment by brynwhyman** [comment]
> Blocked on silverstripe-elemental having php 8 support

Issue to cover that work: https://github.com/silverstripe/silverstripe-elemental/issues/866

**Comment by brynwhyman** [comment]
I can't work out why this issue is actually blocked by PHP 8 support. The PR referenced in the description resolved the test failure referenced in this issue. I've restarted the build to check that's still the case.

It's still got a PHP8 test failure but that looks unrelated. Ideally we can get this merged separately and progressively get the builds green.

**Comment by brynwhyman** [comment]
PR needs to be updated to use the new i click the element implementation in behat-extension
